// Copyright (C) Sportradar AG.See LICENSE for full license governing this code

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Xml.Serialization;
using Sportradar.OddsFeed.SDK.Messages.Feed;

// ReSharper disable InconsistentNaming

namespace Sportradar.OddsFeed.SDK.Messages.Rest
{

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class cashout {

        private restSportEventStatus sport_event_statusField;

        private cashoutOdds oddsField;

        private int productField;

        private string event_idField;

        private long timestampField;

        private long request_idField;

        private bool request_idFieldSpecified;

        /// <remarks/>
        public restSportEventStatus sport_event_status {
            get {
                return this.sport_event_statusField;
            }
            set {
                this.sport_event_statusField = value;
            }
        }

        /// <remarks/>
        public cashoutOdds odds {
            get {
                return this.oddsField;
            }
            set {
                this.oddsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string event_id {
            get {
                return this.event_idField;
            }
            set {
                this.event_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long request_id {
            get {
                return this.request_idField;
            }
            set {
                this.request_idField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool request_idSpecified {
            get {
                return this.request_idFieldSpecified;
            }
            set {
                this.request_idFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    public partial class cashoutOdds {

        private oddsChangeMarket[] marketField;

        private int betting_statusField;

        private bool betting_statusFieldSpecified;

        private int betstop_reasonField;

        private bool betstop_reasonFieldSpecified;

        /// <remarks/>
        [XmlElement("market")]
        public oddsChangeMarket[] market {
            get {
                return this.marketField;
            }
            set {
                this.marketField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int betting_status {
            get {
                return this.betting_statusField;
            }
            set {
                this.betting_statusField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool betting_statusSpecified {
            get {
                return this.betting_statusFieldSpecified;
            }
            set {
                this.betting_statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int betstop_reason {
            get {
                return this.betstop_reasonField;
            }
            set {
                this.betstop_reasonField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool betstop_reasonSpecified {
            get {
                return this.betstop_reasonFieldSpecified;
            }
            set {
                this.betstop_reasonFieldSpecified = value;
            }
        }
    }
}
