// Copyright (C) Sportradar AG.See LICENSE for full license governing this code

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

// ReSharper disable InconsistentNaming

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Xml.Serialization;

// ReSharper disable PartialTypeWithSinglePart
#pragma warning disable CS1591

namespace Sportradar.OddsFeed.SDK.Messages.Rest
{
    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class response {

        private string actionField;

        private string messageField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }

        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    public enum response_code {

        /// <remarks/>
        OK,

        /// <remarks/>
        CREATED,

        /// <remarks/>
        ACCEPTED,

        /// <remarks/>
        FORBIDDEN,

        /// <remarks/>
        NOT_FOUND,

        /// <remarks/>
        CONFLICT,

        /// <remarks/>
        SERVICE_UNAVAILABLE,

        /// <remarks/>
        NOT_IMPLEMENTED,

        /// <remarks/>
        MOVED_PERMANENTLY,

        /// <remarks/>
        BAD_REQUEST,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    public partial class desc_variant {

        private desc_variant_outcomesOutcome[] outcomesField;

        private variant_mappingsMapping[] mappingsField;

        private string idField;

        /// <remarks/>
        [XmlArrayItem("outcome", IsNullable=false)]
        public desc_variant_outcomesOutcome[] outcomes {
            get {
                return this.outcomesField;
            }
            set {
                this.outcomesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("mapping", IsNullable=false)]
        public variant_mappingsMapping[] mappings {
            get {
                return this.mappingsField;
            }
            set {
                this.mappingsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class desc_variant_outcomesOutcome {

        private string idField;

        private string nameField;

        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class variant_mappingsMapping {

        private variant_mappingsMappingMapping_outcome[] mapping_outcomeField;

        private int product_idField;

        private string product_idsField;

        private string sport_idField;

        private string market_idField;

        private string sov_templateField;

        private string valid_forField;

        private string product_market_idField;

        /// <remarks/>
        [XmlElement("mapping_outcome")]
        public variant_mappingsMappingMapping_outcome[] mapping_outcome {
            get {
                return this.mapping_outcomeField;
            }
            set {
                this.mapping_outcomeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                this.product_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string product_ids {
            get {
                return this.product_idsField;
            }
            set {
                this.product_idsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string sport_id {
            get {
                return this.sport_idField;
            }
            set {
                this.sport_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string market_id {
            get {
                return this.market_idField;
            }
            set {
                this.market_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string sov_template {
            get {
                return this.sov_templateField;
            }
            set {
                this.sov_templateField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string valid_for {
            get {
                return this.valid_forField;
            }
            set {
                this.valid_forField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string product_market_id {
            get {
                return this.product_market_idField;
            }
            set {
                this.product_market_idField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class variant_mappingsMappingMapping_outcome {

        private string outcome_idField;

        private string product_outcome_idField;

        private string product_outcome_nameField;

        /// <remarks/>
        [XmlAttribute()]
        public string outcome_id {
            get {
                return this.outcome_idField;
            }
            set {
                this.outcome_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string product_outcome_id {
            get {
                return this.product_outcome_idField;
            }
            set {
                this.product_outcome_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string product_outcome_name {
            get {
                return this.product_outcome_nameField;
            }
            set {
                this.product_outcome_nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class producer {

        private long idField;

        private string nameField;

        private string descriptionField;

        private string api_urlField;

        private bool activeField;

        private string scopeField;

        private int stateful_recovery_window_in_minutesField;
        
        /// <remarks/>
        [XmlAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string api_url {
            get {
                return this.api_urlField;
            }
            set {
                this.api_urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public int stateful_recovery_window_in_minutes {
            get {
                return this.stateful_recovery_window_in_minutesField;
            }
            set {
                this.stateful_recovery_window_in_minutesField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class desc_void_reason {

        private long idField;

        private string descriptionField;

        /// <remarks/>
        [XmlAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class desc_match_status {

        private desc_match_statusSports sportsField;
        
        private long idField;

        private string descriptionField;

        private int period_numberField;

        private bool period_numberFieldSpecified;

        /// <remarks/>
        public desc_match_statusSports sports {
            get {
                return this.sportsField;
            }
            set {
                this.sportsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int period_number {
            get {
                return this.period_numberField;
            }
            set {
                this.period_numberField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool period_numberSpecified {
            get {
                return this.period_numberFieldSpecified;
            }
            set {
                this.period_numberFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class desc_match_statusSports {
        
        private desc_match_statusSportsSport[] sportField;
        
        private bool allField;
        
        public desc_match_statusSports() {
            this.allField = false;
        }
        
        /// <remarks/>
        [XmlElement("sport")]
        public desc_match_statusSportsSport[] sport {
            get {
                return this.sportField;
            }
            set {
                this.sportField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(false)]
        public bool all {
            get {
                return this.allField;
            }
            set {
                this.allField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class desc_match_statusSportsSport {
        
        private string idField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class desc_betting_status {

        private long idField;

        private string descriptionField;

        /// <remarks/>
        [XmlAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class desc_outcome_reason {

        private long idField;

        private string descriptionField;

        /// <remarks/>
        [XmlAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class desc_betstop_reason {

        private long idField;

        private string descriptionField;

        /// <remarks/>
        [XmlAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class desc_market {

        private desc_outcomesOutcome[] outcomesField;

        private desc_specifiersSpecifier[] specifiersField;

        private mappingsMapping[] mappingsField;

        private attributesAttribute[] attributesField;

        private int idField;

        private string nameField;

        private string groupsField;

        private string descriptionField;

        private string includes_outcomes_of_typeField;

        private string variantField;

        private string outcome_typeField;
        
        /// <remarks/>
        [XmlArrayItem("outcome", IsNullable=false)]
        public desc_outcomesOutcome[] outcomes {
            get {
                return this.outcomesField;
            }
            set {
                this.outcomesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("specifier", IsNullable=false)]
        public desc_specifiersSpecifier[] specifiers {
            get {
                return this.specifiersField;
            }
            set {
                this.specifiersField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("mapping", IsNullable=false)]
        public mappingsMapping[] mappings {
            get {
                return this.mappingsField;
            }
            set {
                this.mappingsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("attribute", IsNullable=false)]
        public attributesAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string includes_outcomes_of_type {
            get {
                return this.includes_outcomes_of_typeField;
            }
            set {
                this.includes_outcomes_of_typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string variant {
            get {
                return this.variantField;
            }
            set {
                this.variantField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string outcome_type {
            get {
                return this.outcome_typeField;
            }
            set {
                this.outcome_typeField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class desc_outcomesOutcome {

        private string idField;

        private string nameField;

        private string descriptionField;

        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class desc_specifiersSpecifier {

        private string nameField;

        private string typeField;

        private string descriptionField;

        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class mappingsMapping {

        private mappingsMappingMapping_outcome[] mapping_outcomeField;

        private int product_idField;

        private string product_idsField;

        private string sport_idField;

        private string market_idField;

        private string sov_templateField;

        private string valid_forField;

        /// <remarks/>
        [XmlElement("mapping_outcome")]
        public mappingsMappingMapping_outcome[] mapping_outcome {
            get {
                return this.mapping_outcomeField;
            }
            set {
                this.mapping_outcomeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                this.product_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string product_ids {
            get {
                return this.product_idsField;
            }
            set {
                this.product_idsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string sport_id {
            get {
                return this.sport_idField;
            }
            set {
                this.sport_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string market_id {
            get {
                return this.market_idField;
            }
            set {
                this.market_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string sov_template {
            get {
                return this.sov_templateField;
            }
            set {
                this.sov_templateField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string valid_for {
            get {
                return this.valid_forField;
            }
            set {
                this.valid_forField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class mappingsMappingMapping_outcome {

        private string outcome_idField;

        private string product_outcome_idField;

        private string product_outcome_nameField;

        /// <remarks/>
        [XmlAttribute()]
        public string outcome_id {
            get {
                return this.outcome_idField;
            }
            set {
                this.outcome_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string product_outcome_id {
            get {
                return this.product_outcome_idField;
            }
            set {
                this.product_outcome_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string product_outcome_name {
            get {
                return this.product_outcome_nameField;
            }
            set {
                this.product_outcome_nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class attributesAttribute {

        private string nameField;

        private string descriptionField;

        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class bookmaker_details {

        private string messageField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private DateTime expire_atField;

        private bool expire_atFieldSpecified;

        private int bookmaker_idField;

        private bool bookmaker_idFieldSpecified;

        private string virtual_hostField;

        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public DateTime expire_at {
            get {
                return this.expire_atField;
            }
            set {
                this.expire_atField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool expire_atSpecified {
            get {
                return this.expire_atFieldSpecified;
            }
            set {
                this.expire_atFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int bookmaker_id {
            get {
                return this.bookmaker_idField;
            }
            set {
                this.bookmaker_idField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool bookmaker_idSpecified {
            get {
                return this.bookmaker_idFieldSpecified;
            }
            set {
                this.bookmaker_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string virtual_host {
            get {
                return this.virtual_hostField;
            }
            set {
                this.virtual_hostField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class market_descriptions {

        private desc_market[] marketField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string locationField;

        /// <remarks/>
        [XmlElement("market")]
        public desc_market[] market {
            get {
                return this.marketField;
            }
            set {
                this.marketField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class betstop_reasons_descriptions {

        private desc_betstop_reason[] betstop_reasonField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string locationField;

        /// <remarks/>
        [XmlElement("betstop_reason")]
        public desc_betstop_reason[] betstop_reason {
            get {
                return this.betstop_reasonField;
            }
            set {
                this.betstop_reasonField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class outcome_reasons_descriptions {

        private desc_outcome_reason[] outcome_reasonField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string locationField;

        /// <remarks/>
        [XmlElement("outcome_reason")]
        public desc_outcome_reason[] outcome_reason {
            get {
                return this.outcome_reasonField;
            }
            set {
                this.outcome_reasonField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class betting_status_descriptions {

        private desc_betting_status[] betting_statusField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string locationField;

        /// <remarks/>
        [XmlElement("betting_status")]
        public desc_betting_status[] betting_status {
            get {
                return this.betting_statusField;
            }
            set {
                this.betting_statusField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class match_status_descriptions {

        private desc_match_status[] match_statusField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string locationField;

        /// <remarks/>
        [XmlElement("match_status")]
        public desc_match_status[] match_status {
            get {
                return this.match_statusField;
            }
            set {
                this.match_statusField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class void_reasons_descriptions {

        private desc_void_reason[] void_reasonField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string locationField;

        /// <remarks/>
        [XmlElement("void_reason")]
        public desc_void_reason[] void_reason {
            get {
                return this.void_reasonField;
            }
            set {
                this.void_reasonField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class producers {

        private producer[] producerField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string locationField;

        /// <remarks/>
        [XmlElement("producer")]
        public producer[] producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class variant_descriptions {

        private desc_variant[] variantField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks/>
        [XmlElement("variant")]
        public desc_variant[] variant {
            get {
                return this.variantField;
            }
            set {
                this.variantField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public response_code response_code {
            get {
                return this.response_codeField;
            }
            set {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool response_codeSpecified {
            get {
                return this.response_codeFieldSpecified;
            }
            set {
                this.response_codeFieldSpecified = value;
            }
        }
    }
}
