// Copyright (C) Sportradar AG.See LICENSE for full license governing this code

namespace Sportradar.OddsFeed.SDK.Entities.Enums
{
    /// <summary>
    /// Enumerates possible reasons why the odds-change was generated
    /// </summary>
    public enum OddsChangeReason
    {
        /// <summary>
        /// Indicates the message was generated by normal service execution
        /// </summary>
        Normal,

        /// <summary>
        /// Indicates the message was generated due to risk adjustment
        /// </summary>
        RiskAdjustment,

        /// <summary>
        /// Indicates the message was generated because the feed system went down
        /// </summary>
        SystemDown
    }
}
