// Copyright (C) Sportradar AG.See LICENSE for full license governing this code

using System;

namespace Sportradar.OddsFeed.SDK.Entities.Rest.CustomBet
{
    /// <summary>
    /// Represents a prebuilt bets response returned by the Custom Bet API.
    /// </summary>
    public interface IPrebuiltBets
    {
        /// <summary>
        /// Returns the list of event recommendations
        /// </summary>
        IEventRecommendations[] Events { get; }

        /// <summary>
        /// Returns the number of requested recommendations
        /// </summary>
        int RequestedRecommendations { get; }

        /// <summary>
        /// Returns the date and time when the response was generated by the server, in ISO 8601 format
        /// </summary>
        DateTime? GeneratedAt { get; }
    }
}
